version: '3.8'
services:
  app:
    image: node:20-alpine
    container_name: catalogo-vibe
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./src/images:/app/images
    ports:
      - "5173:5173"
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - VITE_API_KEY=your_api_key_here
      - VITE_AUTH_DOMAIN=your_auth_domain_here
      - VITE_PROJECT_ID=your_project_id_here
      - VITE_MESSAGING_SENDER_ID=your_sender_id_here
      - VITE_APP_ID=your_app_id_here
      - VITE_ADMIN_PASS=your_admin_pass_here

volumes:
  node_modules:
